'use strict';

var template = require('./template');
var utils = require('./utils');

module.exports = function(locals) {

    var config = this.config;
    // Exclude some links generated by Hexo from the Sitemap
    var skipRenderList = [
        '**/*.js',
        '**/*.css'
    ];

    if (Array.isArray(config.skip_render)) {
        skipRenderList = skipRenderList.concat(config.skip_render);
    } else if (config.skip_render != null) {
        skipRenderList.push(config.skip_render);
    }
    /** Iterate on posts to obtain a category list */
    var sitemapCategoryEntries = utils.obtainCategoryList(locals.posts);

    var posts = utils.filterAndSortLinks(
        locals.posts.toArray(),
        locals.pages.toArray(),
        skipRenderList
    );

    var xml = template().render({
        config: config,
        posts: posts,
        categories: sitemapCategoryEntries
    });

    return {
        path: config.sitemap.path,
        data: xml
    };
};